import type { Metadata } from "next";
import { Providers } from "@/app/Providers";
import { headers } from "next/headers";

import "@rainbow-me/rainbowkit/styles.css";
import "@boostxyz/boost-ui/typography/fonts.css";
import "@boostxyz/boost-ui/styles/colors.css";
import "@boostxyz/boost-ui/styles/theme.css";
import "./globals.css";
import { Footer } from "@/app/Footer";
import { Header } from "@/app/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "missioncoin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerz = await headers();

  return (
    <html lang="en" id="app">
      <body className="antialiased">
        <Providers cookie={headerz.get("cookie")}>
          <main className="grid grid-rows-[auto_1fr_auto] min-h-[100lvh] p-10">
            <Header />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
