import type { Metadata } from "next";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Providers } from "@/app/Providers";
import { headers } from "next/headers";

import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "missioncoin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerz = await headers();

  return (
    <html lang="en">
      <body className="antialiased">
        <Providers cookie={headerz.get("cookie")}>
          <ConnectButton />
          {children}
        </Providers>
      </body>
    </html>
  );
}
